a=input("Enter your Name:")
b=input("Enter your age:")
c=input("Enter your Qualification:")
d=input("Enter your Mother name:")
e=input("Enter your Father name:")
f=input("Enter your Percentage:")
g=input("Enter your college name:")
h=input("Enter your Skills:")
i=input("Enter your home address:")
j=input("Enter your school name:")
print("Name:"+a)
print("Age:"+b)
print("Qualificaion:"+c)
print("Mother name:"+d)
print("Father name:"+e)
print("Percentage"+f)
print("College:"+g)
print("Skills:"+h)
print("Address:"+i)
print("School:"+j)